http://master-rfb67c2xwnqk6.eu.platform.sh/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: true
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  type: upstream
  upstream: ''
http://www.{default}/:
  to: http://{default}/
  type: redirect
http://{default}/:
  cache:
    enabled: true
  ssi:
    enabled: false
  type: upstream
  upstream: php:php
